version: '3.8'

services:
  postgres:
    image: postgres:15.5-alpine3.19
    container_name: booking_dev_postgres
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "16000:5432"
    networks:
      - booking_dev_network
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  booking_dev_network:
    driver: bridge

volumes:
  postgres:
    driver: local
